### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by amarvin** [mathebox/django_hana_pyhdb#3]
Django_hana_pyhdb doesn't seem to be compatible with Python 3, but it's a very nice library. Do you have a plan to add such support?

I installed it for my Django 1.10 project running in Python 3.5, and tried to make a migration and got this error:

  File "C:\Users\MarvinW\AppData\Local\Continuum\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\users\marvinw\documents\visual studio 2015\Projects\TestingDjangoHANA\TestingDjangoHANA\env\lib\site-packages\django_hana-1.1-py3.5.egg\django_hana\compiler.py", line 1, in <module>
    from itertools import izip
ImportError: cannot import name 'izip'
The Python REPL process has exited

**Comment by mathebox** [comment]
Hi @amarvin!
Sorry for the late response. Before fixing this, I wanted to create a acceptable testing setup. Currently there are only few tests. But your error should be fixed.
Please check again with the latest version. Feel free to reopen this issue if you still get errors.

**Comment by amarvin** [comment]
Nice work creating an update so quickly. Thanks! I think there are still two things to fix though.

Firstly, Django_hana_pyhdb produces a lot of "Map" datatypes as SQL parameters, but Django and Pyhdb throw errors with that data type (e.g. normally built to use lists, rather than maps). I've tried editing base.py to detect map objects in the variable "params" and convert them to list, but that doesn't always work. Are you testing with specific versions? I'm using Django 1.10.5 and Pyhdb 0.3.2.

Secondly, for datetime fields, Pyhdb seems to be built just for format
`"%Y-%m-%d %H:%M:%S.%f"`
but for a few tables (e.g. DJANGO_MIGRATIONS), django_hana_pyhdb sends it the current time as:
'2017-02-06 20:17:42.793209+00:00'
and then Pyhdb throws an error in types.py when using datetime.datetime.strptime, because it doesn't know what to do with the "+00:00" part.

**Comment by amarvin** [comment]
For the first bug, here's why my initial Django makemigration currently errors out. I added some print statements in django_hana_pyhdb in base.py. The error is when this SQL statement is attempted:
`INSERT INTO "AUTH_PERMISSION" (id,"NAME", "CONTENT_TYPE_ID", "CODENAME") VALUES (auth_permission_id_seq.nextval, %s, %s, %s)`
with parameters:
`[<map object at 0x000000BEDD8FB1D0>, <map object at 0x000000BEDD8FB240>, <map object at 0x000000BEDD8FB2B0>]`

then later Pyhdb tries to convert the parameters to integers, yielding the error:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'map'

It turns out that the send map object contains:
["Can change log entry", 1, "change_logentry"]

**Comment by mathebox** [comment]
For the first bug: I ran into similar problems which I could resolve by using list comprehensions. Could you please send the stack trace?

For the second bug: Have you disabled the timezone support?
see Readme:
> 4. HANA doesn't support Timezone. Set USE_TZ=False in settings.py.

Please note: There are also `basestring` and `unicode` calls. So Python 3 will break here again. I will fix this in my spare time. But you are welcomed to create pull requests and issues.
As you can see, this project still has a poor code coverage. The reason is partly that you can't use SAP HANA easily with CI servers like travis. So you can't just create a django project and run all the commands. To support multiple python and django versions, I choose to create integrity tests which ensure a consistent behavior that has to be tested manually with SAP HANA.

**Comment by amarvin** [comment]
Nice, that fixed the second bug.

For the second bug, here is the log file (debug level) when I run makemigrations the first time:

(0.099) QUERY = "select (1) as a from schemas where schema_name='TACPLAN_D01'" - PARAMS = (); args=()
(0.093) QUERY = 'set schema TACPLAN_D01' - PARAMS = (); args=()
(0.090) QUERY = "select table_name, 't' from tables where schema_name='TACPLAN_D01' UNION select view_name, 'v' from views where schema_name='TACPLAN_D01'" - PARAMS = (); args=()
(0.092) QUERY = 'SELECT "DJANGO_MIGRATIONS"."APP", "DJANGO_MIGRATIONS"."NAME" FROM "DJANGO_MIGRATIONS"' - PARAMS = (); args=()
(0.089) QUERY = "select table_name, 't' from tables where schema_name='TACPLAN_D01' UNION select view_name, 'v' from views where schema_name='TACPLAN_D01'" - PARAMS = (); args=()
(0.091) QUERY = 'SELECT "DJANGO_MIGRATIONS"."APP", "DJANGO_MIGRATIONS"."NAME" FROM "DJANGO_MIGRATIONS"' - PARAMS = (); args=()
(0.089) QUERY = "select table_name, 't' from tables where schema_name='TACPLAN_D01' UNION select view_name, 'v' from views where schema_name='TACPLAN_D01'" - PARAMS = (); args=()
(0.090) QUERY = 'SELECT "DJANGO_MIGRATIONS"."APP", "DJANGO_MIGRATIONS"."NAME" FROM "DJANGO_MIGRATIONS"' - PARAMS = (); args=()
(0.180) QUERY = 'SELECT "DJANGO_CONTENT_TYPE"."ID", "DJANGO_CONTENT_TYPE"."APP_LABEL", "DJANGO_CONTENT_TYPE"."MODEL" FROM "DJANGO_CONTENT_TYPE" WHERE ("DJANGO_CONTENT_TYPE"."APP_LABEL" = %s AND "DJANGO_CONTENT_TYPE"."MODEL" = %s)' - PARAMS = ('admin', 'logentry'); args=('admin', 'logentry')
(0.189) QUERY = 'SELECT "AUTH_PERMISSION"."CONTENT_TYPE_ID", "AUTH_PERMISSION"."CODENAME" FROM "AUTH_PERMISSION" INNER JOIN "DJANGO_CONTENT_TYPE" ON ("AUTH_PERMISSION"."CONTENT_TYPE_ID" = "DJANGO_CONTENT_TYPE"."ID") WHERE "AUTH_PERMISSION"."CONTENT_TYPE_ID" IN (%s) ORDER BY "DJANGO_CONTENT_TYPE"."APP_LABEL" ASC, "DJANGO_CONTENT_TYPE"."MODEL" ASC, "AUTH_PERMISSION"."CODENAME" ASC' - PARAMS = (1,); args=(1,)
(0.089) QUERY = 'INSERT INTO "AUTH_PERMISSION" (id,"NAME", "CONTENT_TYPE_ID", "CODENAME") VALUES (auth_permission_id_seq.nextval, %s, %s, %s)' - PARAMS = ('<map object at 0x00000030BB0CD5C0>', '<map object at 0x00000030BB0CD2E8>', '<map object at 0x00000030BB0CDAC8>'); args=(<map object at 0x00000030BB0CD5C0>, <map object at 0x00000030BB0CD2E8>, <map object at 0x00000030BB0CDAC8>)

and the console displays:

Executing manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\core\management\__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\core\management\base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\core\management\base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\core\management\commands\migrate.py", line 224, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\core\management\sql.py", line 53, in emit_post_migrate_signal
    **kwargs
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\dispatch\dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\contrib\auth\management\__init__.py", line 83, in create_permissions
    Permission.objects.using(using).bulk_create(perms)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\db\models\query.py", line 452, in bulk_create
    ids = self._batched_insert(objs_without_pk, fields, batch_size)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\db\models\query.py", line 1068, in _batched_insert
    self._insert(item, fields=fields, using=self.db)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\db\models\query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\django-hana\django_hana\compiler.py", line 99, in execute_sql
    cursor.execute(sql, params)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\django-hana\django_hana\base.py", line 122, in execute
    return CursorWrapper.execute(self, sql, params)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\django-hana\django_hana\base.py", line 88, in execute
    self.cursor.execute(self._replace_params(sql), params)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\cursor.py", line 260, in execute
    self.executemany(statement, parameters=[parameters])
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\cursor.py", line 284, in executemany
    self.execute_prepared(prepared_statement, parameters)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\cursor.py", line 189, in execute_prepared
    reply = self.connection.send_request(request)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\connection.py", line 83, in send_request
    payload = message.pack()  # obtain BytesIO instance
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\protocol\message.py", line 55, in pack
    self.build_payload(payload)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\protocol\message.py", line 45, in build_payload
    segment.pack(payload, commit=self.autocommit)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\protocol\segments.py", line 94, in pack
    self.build_payload(payload)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\protocol\segments.py", line 80, in build_payload
    part_payload = part.pack(remaining_size)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\protocol\parts.py", line 103, in pack
    arguments_count, payload = self.pack_data(remaining_size - self.header_size)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\protocol\parts.py", line 502, in pack_data
    pfield = _DataType.prepare(value)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\protocol\types.py", line 115, in prepare
    pfield += cls._struct.pack(int(value))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'map'
The Python REPL process has exited

**Comment by amarvin** [comment]
Oops, ignore my last log and console output. I forgot to delete all the SAP HANA tables and sequences beforehand, from my previously failed "manage.py migrate". After deleting those tables and sequences, and then running "manage.py migrate", 
**I get this log:**

`(0.099) QUERY = "select (1) as a from schemas where schema_name='TACPLAN_D01'" - PARAMS = (); args=()
(0.094) QUERY = 'set schema TACPLAN_D01' - PARAMS = (); args=()
(0.090) QUERY = "select table_name, 't' from tables where schema_name='TACPLAN_D01' UNION select view_name, 'v' from views where schema_name='TACPLAN_D01'" - PARAMS = (); args=()
CREATE COLUMN TABLE "DJANGO_MIGRATIONS" ("ID" integer NOT NULL PRIMARY KEY, "APP" nvarchar(255) NOT NULL, "NAME" nvarchar(255) NOT NULL, "APPLIED" timestamp NOT NULL); (params None)
(0.152) QUERY = 'CREATE COLUMN TABLE "DJANGO_MIGRATIONS" ("ID" integer NOT NULL PRIMARY KEY, "APP" nvarchar(255) NOT NULL, "NAME" nvarchar(255) NOT NULL, "APPLIED" timestamp NOT NULL)' - PARAMS = (); args=None
CREATE SEQUENCE "DJANGO_MIGRATIONS_ID_SEQ" RESET BY SELECT IFNULL(MAX("ID"),0) + 1 FROM "DJANGO_MIGRATIONS"; (params [])
(0.117) QUERY = 'CREATE SEQUENCE "DJANGO_MIGRATIONS_ID_SEQ" RESET BY SELECT IFNULL(MAX("ID"),0) + 1 FROM "DJANGO_MIGRATIONS"' - PARAMS = (); args=[]
(0.101) QUERY = 'SELECT "DJANGO_MIGRATIONS"."APP", "DJANGO_MIGRATIONS"."NAME" FROM "DJANGO_MIGRATIONS"' - PARAMS = (); args=()
(0.100) QUERY = "select (1) as a from schemas where schema_name='TACPLAN_D01'" - PARAMS = (); args=()
(0.097) QUERY = 'set schema TACPLAN_D01' - PARAMS = (); args=()
(0.091) QUERY = "select table_name, 't' from tables where schema_name='TACPLAN_D01' UNION select view_name, 'v' from views where schema_name='TACPLAN_D01'" - PARAMS = (); args=()
(0.092) QUERY = 'SELECT "DJANGO_MIGRATIONS"."APP", "DJANGO_MIGRATIONS"."NAME" FROM "DJANGO_MIGRATIONS"' - PARAMS = (); args=()
(0.091) QUERY = "select table_name, 't' from tables where schema_name='TACPLAN_D01' UNION select view_name, 'v' from views where schema_name='TACPLAN_D01'" - PARAMS = (); args=()
(0.092) QUERY = 'SELECT "DJANGO_MIGRATIONS"."APP", "DJANGO_MIGRATIONS"."NAME" FROM "DJANGO_MIGRATIONS"' - PARAMS = (); args=()
CREATE COLUMN TABLE "DJANGO_CONTENT_TYPE" ("ID" integer NOT NULL PRIMARY KEY, "NAME" nvarchar(100) NOT NULL, "APP_LABEL" nvarchar(100) NOT NULL, "MODEL" nvarchar(100) NOT NULL); (params None)
(0.110) QUERY = 'CREATE COLUMN TABLE "DJANGO_CONTENT_TYPE" ("ID" integer NOT NULL PRIMARY KEY, "NAME" nvarchar(100) NOT NULL, "APP_LABEL" nvarchar(100) NOT NULL, "MODEL" nvarchar(100) NOT NULL)' - PARAMS = (); args=None
ALTER TABLE "DJANGO_CONTENT_TYPE" ADD CONSTRAINT "DJANGO_CONTENT_TYPE_APP_LABEL_76BD3D3B_UNIQ" UNIQUE ("APP_LABEL", "MODEL"); (params [])
(0.147) QUERY = 'ALTER TABLE "DJANGO_CONTENT_TYPE" ADD CONSTRAINT "DJANGO_CONTENT_TYPE_APP_LABEL_76BD3D3B_UNIQ" UNIQUE ("APP_LABEL", "MODEL")' - PARAMS = (); args=[]
CREATE SEQUENCE "DJANGO_CONTENT_TYPE_ID_SEQ" RESET BY SELECT IFNULL(MAX("ID"),0) + 1 FROM "DJANGO_CONTENT_TYPE"; (params [])
(0.112) QUERY = 'CREATE SEQUENCE "DJANGO_CONTENT_TYPE_ID_SEQ" RESET BY SELECT IFNULL(MAX("ID"),0) + 1 FROM "DJANGO_CONTENT_TYPE"' - PARAMS = (); args=[]
(0.091) QUERY = "select table_name, 't' from tables where schema_name='TACPLAN_D01' UNION select view_name, 'v' from views where schema_name='TACPLAN_D01'" - PARAMS = (); args=()
(0.095) QUERY = 'INSERT INTO "DJANGO_MIGRATIONS" (id,"APP", "NAME", "APPLIED") VALUES (django_migrations_id_seq.nextval, %s, %s, %s)' - PARAMS = ['contenttypes', '0001_initial', '2017-02-07 09:45:19.129957']; args=<map object at 0x00000054B8F38B70>`

**and this console:**

`Executing manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\django-hana\django_hana\base.py", line 88, in execute
    self.cursor.execute(self._replace_params(sql), params)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\cursor.py", line 260, in execute
    self.executemany(statement, parameters=[parameters])
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\cursor.py", line 284, in executemany
    self.execute_prepared(prepared_statement, parameters)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\cursor.py", line 189, in execute_prepared
    reply = self.connection.send_request(request)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\connection.py", line 83, in send_request
    payload = message.pack()  # obtain BytesIO instance
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\protocol\message.py", line 55, in pack
    self.build_payload(payload)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\protocol\message.py", line 45, in build_payload
    segment.pack(payload, commit=self.autocommit)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\protocol\segments.py", line 94, in pack
    self.build_payload(payload)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\protocol\segments.py", line 80, in build_payload
    part_payload = part.pack(remaining_size)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\protocol\parts.py", line 103, in pack
    arguments_count, payload = self.pack_data(remaining_size - self.header_size)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\protocol\parts.py", line 481, in pack_data
    for row_parameters in self.parameters:
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\pyhdb\pyhdb\cursor.py", line 97, in __next__
    type(parameters).__name__)
pyhdb.exceptions.ProgrammingError: Prepared statement parameters supplied as map, shall be list, tuple or dict.`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\core\management\__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\core\management\base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\core\management\base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\core\management\commands\migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\db\migrations\executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\db\migrations\executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\db\migrations\executor.py", line 250, in apply_migration
    self.recorder.record_applied(migration.app_label, migration.name)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\db\migrations\recorder.py", line 73, in record_applied
    self.migration_qs.create(app=app, name=name)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\db\models\query.py", line 399, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\db\models\base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\db\models\base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\db\models\base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\db\models\base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\MarvinW\Desktop\TacticalPlanner\Django-HANA\DjangoWebProject1\DjangoWebProject1\env\lib\site-packages\django\db\models\query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\django-hana\django_hana\compiler.py", line 99, in execute_sql
    cursor.execute(sql, params)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\django-hana\django_hana\base.py", line 122, in execute
    return CursorWrapper.execute(self, sql, params)
  File "c:\users\marvinw\desktop\tacticalplanner\django-hana\djangowebproject1\djangowebproject1\env\src\django-hana\django_hana\base.py", line 94, in execute
    if e[0] in self.codes_for_integrityerror:
TypeError: 'ProgrammingError' object does not support indexing
The Python REPL process has exited`

**Comment by amarvin** [comment]
OK, I managed to fix the second issue with a change to django-hana-pyhdb. Let me know if these make sense. I'm pretty new to contributing on GitHub, so I don't know how to make the changes myself (probably as a pull request with a commit, I guess?). Apologies for that. You really created an excellent package here though, thanks!

**compiler.py line 96:** (replace everything within the "for sql, params in self.as_sql():" code block with these lines. There is probably a simpler way to do this...)
```
                from django.utils.encoding import force_text
                def to_unicode(s):
                    return force_text(s, strings_only=True, errors='replace')
                if isinstance(params, list):
                    if isinstance(params[0], list):
                        cursor.executemany(sql, params)
                    else:
                        cursor.execute(sql, params)
                elif isinstance(params, tuple):
                    if len(params)>1 and isinstance(params[0], map):
                        params_list = []
                        for vals in params:
                            params_list.append(tuple(to_unicode(val) for val in vals))
                        cursor.executemany(sql, params_list)
                    else:
                        params = tuple(to_unicode(val) for val in params)
                        cursor.execute(sql, params)
                elif params is None:
                    params = ()
                    cursor.execute(sql, params)
                elif isinstance(params, dict):
                    params = {to_unicode(k): to_unicode(v) for k, v in params.items()}
                    cursor.execute(sql, params)
                elif isinstance(params, map):
                    params = list(to_unicode(val) for val in params)
                    cursor.execute(sql, params)
```
where the syntax is inspired by what was done in the Django development (see BaseDatabaseOperations.last_executed_query): https://github.com/django/django/blob/cecc079168e8669138728d31611ff3a1e7eb3a9f/django/db/backends/base/operations.py

**Comment by amarvin** [comment]
To get it to work, I also had to make some other small changes:

**schema.py line 51:** (prepare_default(self,value) now contains these lines)
```
        try:
            # Python2
            if isinstance(value, basestring):
                return '"%s"' % (value,)
        except NameError:
            # Python3
            if isinstance(value, str):
                return '"%s"' % (value,)
        return str(value)
```

**base.py line 94:** (Django integrityerror isn't indexable in my version of Django)
```
            try:
                if e[0] in self.codes_for_integrityerror:
                    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
            except TypeError:
                if e in self.codes_for_integrityerror:
                    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
```

**Comment by amarvin** [comment]
The edit in **compiler.py** isn't needed if you instead make a change in **operations.py** line 225, from:
`insert_param_groups.append(map(self.sanitize_bool, p))`
to:
`insert_param_groups.append(list(map(self.sanitize_bool, p)))`
to prevent map objects being passed as parameters in Python 3 (note that the map function was changed between Python 2 and Python 3).

The edit in **schema.py** is no longer needed, due to commit https://github.com/mathebox/django_hana_pyhdb/commit/c9f358912e844ba698c769a3c1a007950c1f7c36.

The commit in **base.py** might still be needed -- you should consider adding a test that creates an IntegrityError.
